### ISSUE TITLE
Dead or planned to finish at some point? (Migration)

### ISSUE THREAD

**Issue by KiriCattus** [proxysprojects/MoreCraftingTables#1]
Do either of you think that you may continue this project at one point if so would you like me to transfer it to you?
I am clearing out old projects and as I didn't contribute to this one I feel you should have the chance to download it before I clear it off.

**Comment by Mohron** [comment]
If MrIbby doesn't chime in, I'll take it. no reason to have all our work just deleted so you can clean house.

**Comment by KiriCattus** [comment]
My aim is to get it back to one of you both since I can't do anything with it. Might as well put it to some use rather than waste it sittin with me but the last I heard of Ibby was about a week or two ago and I think he was planning to retire from modding for Minecraft but I'll ping him again and double check.

**Comment by Mohron** [comment]
Well I never plan to work on normal client mods, this is a special case since it's more focused on servers/packs doing custom recipes. Otherwise I'll just continue working on primarily server-side tech.

**Comment by KiriCattus** [comment]
There has been no reply within 13 days so I will transfer MoreCraftingTables over to a repo of your choosing when you are ready @Mohron I wish you good luck getting the last of it working, It should be nice to see out there in the future
